// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function Parse(arg1:string):Promise<parser.ParseResult>;

export function ParseFile(arg1:string):Promise<parser.ParseResult>;

export function ReadFile(arg1:string):Promise<string>;
